# Generated by Django 4.2.10 on 2024-07-17 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("campanas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcampana",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="BBVATLMFormalizadas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dni", models.CharField(max_length=20)),
                ("fecha", models.DateTimeField()),
                ("tarjeta_wf", models.CharField(max_length=100)),
                ("tipo_captacion", models.CharField(max_length=100)),
                ("periodo", models.CharField(max_length=50)),
                ("num_operaciones", models.IntegerField()),
                ("fecha_activacion", models.DateTimeField()),
                ("periodo_activacion", models.CharField(max_length=50)),
                (
                    "subcampaña",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campanas.subcampana",
                    ),
                ),
            ],
            options={
                "db_table": "bbva_tlm_formalizadas",
                "unique_together": {("dni", "periodo", "fecha")},
            },
        ),
    ]
