# Generated by Django 4.2.10 on 2024-07-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campanas", "0002_subcampana_activo_bbvatlmformalizadas"),
    ]

    operations = [
        migrations.AddField(
            model_name="campana",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="imagenes/"),
        ),
    ]
