# Generated by Django 4.2.10 on 2024-07-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campanas", "0003_campana_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bbvatlmformalizadas",
            name="fecha_activacion",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="bbvatlmformalizadas",
            name="periodo_activacion",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
