# Generated by Django 4.2.10 on 2024-07-17 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("campanas", "0004_alter_bbvatlmformalizadas_fecha_activacion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bbvatlmformalizadas",
            name="subcampaña",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="campanas.subcampana"
            ),
        ),
    ]
