# Generated by Django 4.2.10 on 2024-07-17 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("campanas", "0006_bbvawebformalizadas"),
    ]

    operations = [
        migrations.CreateModel(
            name="BBVAPPDesembolsos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto_desembolso", models.FloatField()),
                ("fecha", models.DateTimeField()),
                ("dni", models.CharField(max_length=20)),
                ("periodo", models.CharField(max_length=50)),
                ("plaza", models.CharField(blank=True, max_length=100, null=True)),
                ("territorio", models.CharField(blank=True, max_length=100, null=True)),
                ("num_operaciones", models.IntegerField(blank=True, null=True)),
                (
                    "subcampaña",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campanas.subcampana",
                    ),
                ),
            ],
            options={
                "db_table": "bbva_pp_desembolsos",
                "unique_together": {("dni", "periodo", "fecha")},
            },
        ),
    ]
