# Generated by Django 4.2.10 on 2024-07-18 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("campanas", "0007_bbvappdesembolsos"),
    ]

    operations = [
        migrations.CreateModel(
            name="SBPTLMAprobadas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dni", models.CharField(max_length=20)),
                ("fecha", models.DateTimeField()),
                ("tipo_tc", models.CharField(blank=True, max_length=100, null=True)),
                ("periodo", models.CharField(max_length=50)),
                ("tiene_oferta_cta_free", models.IntegerField(blank=True, null=True)),
                ("acepta_cta_free", models.IntegerField(blank=True, null=True)),
                ("num_operaciones", models.IntegerField(default=1)),
                (
                    "subcampaña",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campanas.subcampana",
                    ),
                ),
            ],
            options={
                "db_table": "sbp_tlm_aprobadas",
                "unique_together": {("dni", "periodo", "fecha")},
            },
        ),
    ]
