# Generated by Django 4.2.10 on 2024-07-18 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("campanas", "0008_sbptlmaprobadas"),
    ]

    operations = [
        migrations.CreateModel(
            name="SBPPPDesembolsos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nro_sol", models.CharField(max_length=100)),
                ("monto_desembolso", models.FloatField()),
                ("fecha", models.DateTimeField()),
                ("periodo", models.CharField(max_length=50)),
                ("zona", models.CharField(max_length=100)),
                ("num_operaciones", models.IntegerField(default=1)),
                (
                    "subcampaña",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campanas.subcampana",
                    ),
                ),
            ],
            options={
                "db_table": "sbp_pp_desembolsos",
                "unique_together": {("nro_sol", "periodo", "fecha")},
            },
        ),
    ]
