# Generated by Django 4.2.10 on 2024-07-26 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("campanas", "0009_sbpppdesembolsos"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subcampana",
            old_name="campaña",
            new_name="campana_id",
        ),
    ]
