# Generated by Django 4.2.10 on 2024-07-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campanas", "0010_rename_campaña_subcampana_campana_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcampana",
            name="meta",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
