# Generated by Django 4.2.10 on 2024-07-31 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campanas", "0011_subcampana_meta"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcampana",
            name="monto_meta",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="subcampana",
            name="meta",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
